<a href="https://colab.research.google.com/github/k-abhilaasha/Numpy/blob/main/Attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])
arr1.shape

(5,)

In [ ]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr2
# arr2.shape

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr2.ndim

3

In [ ]:
arr2.size

8

In [ ]:
arr2.itemsize

8

In [ ]:
arr6=np.linspace(1,10,5)
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr6.itemsize

In [ ]:
arr6.nbytes

40

In [ ]:
arr6.astype('int')

array([ 1,  3,  5,  7, 10])