<a href="https://colab.research.google.com/github/k-abhilaasha/Numpy/blob/main/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# if both arrays are same shape then boradcasting is not needed
a1=np.arange(6).reshape(3,2)
a2=np.arange(6,12).reshape(3,2)

In [ ]:
a1+a2

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [ ]:
# if x=1,y=m then broadcating takes place
a3=np.arange(3).reshape(1,3)
a4=np.arange(8,14).reshape(2,3)
a3+a4

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
# if x=m,y=1 then broadcating takes place
a5=np.arange(3).reshape(3,1)
a6=np.arange(8,14).reshape(3,2)
a5+a6

array([[ 8,  9],
       [11, 12],
       [14, 15]])

In [ ]:
# if x=1,y=1 it will takes place
a7=np.arange(1).reshape(1,1)
a8=np.arange(8,14).reshape(3,2)
a7+a8

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [ ]:
# if x=1 and y!=n then also operation does not takes place
a9=np.arange(3).reshape(1,3)
a10=np.arange(16).reshape(4,4)
a9+a10

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [ ]:
# if they are different dimensions
a11=np.arange(4)
a12=np.arange(20).reshape(5,4)
a11+a12

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])