In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2
# type(arr2)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5=np.identity(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
arr6=np.linspace(1,10,5)
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr7=arr6.copy()
arr7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])