<a href="https://colab.research.google.com/github/k-abhilaasha/Numpy/blob/main/imp_numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random

In [4]:
np.random.random()

0.7807790657842357

In [22]:
np.random.seed(1)
num=np.random.randint(1,50,10)
num

array([38, 44, 13,  9, 10, 12,  6, 16,  1, 17])

In [14]:
np.random.uniform(3,10)

5.192914618525926

In [29]:
np.random.uniform(1,100,10).reshape(5,2)

array([[83.08554383, 83.13073258],
       [28.03194745,  6.86507693],
       [67.38227597, 59.71348631],
       [67.49375564, 41.76700002],
       [20.5575389 , 29.67333441]])

In [23]:
num.max()

np.int64(44)

In [24]:
np.argmax(num)

np.int64(1)

In [25]:
np.where(num%2==0,num,-1)

array([38, 44, -1, -1, 10, 12,  6, 16, -1, -1])

In [26]:
np.percentile(num,75)

np.float64(16.75)