<a href="https://colab.research.google.com/github/k-abhilaasha/Numpy/blob/main/Indexing%2CSlicing%2CIteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr2=np.arange(1,6)
arr2

array([1, 2, 3, 4, 5])

In [ ]:
arr2[0]

np.int64(1)

In [ ]:
#row indexing
arr1[0]

array([0, 1, 2, 3])

In [ ]:
# row slicing
arr1[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#column slicing
arr1[:,0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [ ]:
# Indexing
arr1[0][3]

np.int64(3)

In [ ]:
arr1[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [ ]:
for i in arr1:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [ ]:
for i in np.nditer(arr1):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
