<a href="https://colab.research.google.com/github/k-abhilaasha/Numpy/blob/main/Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [ ]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [ ]:
arr1+arr2

array([ 5,  7,  9, 11, 13, 15])

In [ ]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [ ]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2>5

array([False, False,  True,  True,  True,  True])

In [ ]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [ ]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [ ]:
arr1.dot(arr2)

np.int64(154)

In [ ]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [ ]:
arr4.min()

np.int64(6)

In [ ]:
arr4.max()

np.int64(11)

In [ ]:
arr4.min(axis=0)

array([6, 7])

In [ ]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [ ]:
arr4.max(axis=0)

array([10, 11])

In [ ]:
arr4.max(axis=1)

array([ 7,  9, 11])

In [ ]:
arr4.sum()

np.int64(51)

In [ ]:
arr4.sum(axis=0)

array([24, 27])

In [ ]:
arr4.sum(axis=1)

array([13, 17, 21])

In [ ]:
arr4.mean()

np.float64(8.5)

In [ ]:
np.median(arr4)

np.float64(8.5)

In [ ]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [ ]:
arr4.std()

np.float64(1.707825127659933)

In [ ]:
np.sqrt(arr4)

array([[2.44948974, 2.64575131],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])

In [ ]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])