<a href="https://colab.research.google.com/github/k-abhilaasha/Numpy/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Level-1
Basics

In [ ]:
import numpy as np

In [ ]:
a=np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(5,)

In [ ]:
a.size

5

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=np.linspace(0,1,5)
b

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a1=np.ones((3,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a2=np.zeros((2,4))
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Level-2
Indexing & Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
arr[0]

np.int64(10)

In [ ]:
arr[-1]

np.int64(70)

In [ ]:
arr[2:6]

array([30, 40, 50, 60])

In [ ]:
arr[0:3]

array([10, 20, 30])

In [ ]:
arr[4:]

array([50, 60, 70])

In [ ]:
arr[::2]

array([10, 30, 50, 70])

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [ ]:
arr[1][1]

np.int64(50)

In [ ]:
arr[2][2]

np.int64(90)

In [ ]:
arr[0]

array([10, 20, 30])

In [ ]:
arr[:,-1]

array([30, 60, 90])

In [ ]:
arr[1:3,1:3]

array([[50, 60],
       [80, 90]])

Level-3
Boolean & Fancy Indexing


In [ ]:
marks = np.array([45, 67, 32, 89, 76, 54, 91, 38])

In [ ]:
marks[marks>60]

array([67, 89, 76, 91])

In [ ]:
marks[marks<40]

array([32, 38])

In [ ]:
marks[(marks>=50)& (marks<=80)]

array([67, 76, 54])

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [ ]:
arr[[0,2,5]]

array([10, 30, 60])

Level-4
Reshape & Manipulation



In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
r=arr2.ravel()
f=arr2.flatten()

In [ ]:
r[0]=100
f[1]=200
print(r)
print(f)
print(arr2)

[100   2   3   4   5   6]
[  1 200   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
np.transpose(arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

Level 5
Statistics

In [ ]:
marks = np.array([45, 67, 32, 89, 76, 54, 91, 38, 82, 71])

In [ ]:
marks.mean()

np.float64(64.5)

In [ ]:
np.median(marks)

np.float64(69.0)

In [ ]:
np.max(marks)

np.int64(91)

In [ ]:
np.min(marks)

np.int64(32)

In [ ]:
np.std(marks)

np.float64(20.096019506359962)

In [ ]:
np.var(marks)

np.float64(403.85)

In [ ]:
np.percentile(marks,25)


np.float64(47.25)

In [ ]:
np.percentile(marks,50)

np.float64(69.0)

In [ ]:
np.percentile(marks,75)

np.float64(80.5)

In [ ]:
np.max(marks)

np.int64(91)

In [ ]:
np.argmax(marks)

np.int64(6)

Level 6
Broadcasting

In [ ]:
prices = np.array([100, 200, 300, 400])
add=np.array([10,20,30,40])
prices+add

array([110, 220, 330, 440])

In [ ]:
prices*1.10

array([110., 220., 330., 440.])

In [ ]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95]
])
add=np.array([5,5,5])
marks+add

array([[ 75,  85,  95],
       [ 65,  80,  90],
       [ 93,  97, 100]])

In [ ]:
marks+5

array([[ 75,  85,  95],
       [ 65,  80,  90],
       [ 93,  97, 100]])

Level 7
Data Analyst-style problem

In [ ]:
attendance = np.array([
    [85, 90, 78, 92],
    [70, 65, 80, 75],
    [95, 88, 91, 94],
    [60, 72, 68, 70]
])

In [ ]:
# average of each student
avg=[]
for i in attendance:
  print(np.average(i))
  avg.append(np.average(i))



86.25
72.5
92.0
67.5


In [ ]:
attendance.mean(axis=1)  # each student

array([86.25, 72.5 , 92.  , 67.5 ])

In [ ]:
attendance.mean(axis=0)  # each subject

array([77.5 , 78.75, 79.25, 82.75])

In [ ]:
# average of each subject
for i in attendance.T:
  print(np.average(i))

77.5
78.75
79.25
82.75


In [ ]:
np.argmax(avg)

np.int64(2)

In [ ]:
# Find which student has the highest average.
np.argmax(attendance.mean(axis=1))

np.int64(2)

In [ ]:
# Find which subject has the lowest average.
np.argmin(attendance.mean(axis=0))

np.int64(0)

In [ ]:
# Find all attendance values below 75.
attendance[attendance<75]

array([70, 65, 60, 72, 68, 70])

In [ ]:
# Count how many attendance values are below 75.
np.sum(attendance<75)

np.int64(6)

In [ ]:
import numpy as np

sales = np.array([
    [1200, 1500, 1100, 1800],
    [900, 1300, 1250, 1600],
    [2000, 2100, 1900, 2200]
])

# 1. Total sales of each salesperson
total_person = sales.sum(axis=1)
print("Total sales of each salesperson:", total_person)

# 2. Average sales of each salesperson
avg_person = sales.mean(axis=1)
print("Average sales of each salesperson:", avg_person)

# 3. Total sales for each month
total_month = sales.sum(axis=0)
print("Total sales for each month:", total_month)

# 4. Best salesperson
best_person = np.argmax(total_person)
print("Best salesperson:", best_person)

# 5. Best month
best_month = np.argmax(total_month)
print("Best month:", best_month)

# 6. All sales above 1500
above_1500 = sales[sales > 1500]
print("Sales above 1500:", above_1500)

# 7. Number of sales above 1500
count = np.sum(sales > 1500)
print("Number of sales above 1500:", count)

# 8. Overall average sales
overall_avg = sales.mean()
print("Overall average sales:", overall_avg)

Total sales of each salesperson: [5600 5050 8200]
Average sales of each salesperson: [1400.  1262.5 2050. ]
Total sales for each month: [4100 4900 4250 5600]
Best salesperson: 2
Best month: 3
Sales above 1500: [1800 1600 2000 2100 1900 2200]
Number of sales above 1500: 6
Overall average sales: 1570.8333333333333
