In [ ]:
import numpy as np

In [ ]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr1.ndim

2

In [ ]:
np.ravel(arr1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
arr2=np.arange(6).reshape(2,3)
arr3=np.arange(6,12).reshape(2,3)

In [ ]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr3

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.hstack((arr2,arr3))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
np.vstack((arr2,arr3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.vsplit(arr2,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [ ]:
np.hsplit(arr2,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [ ]:
np.split(arr1,[2,3])

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]]),
 array([], shape=(0, 2), dtype=int64)]

In [ ]:
# fancy indexing
arr4=np.arange(15).reshape(5,3)
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr4[[0,1,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr4[:,[0,1]]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [ ]:
# indexing with boolean arrays
import numpy as np
# import random
arr=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr

array([[62, 53, 21,  8],
       [87, 56, 24, 53],
       [84, 61, 80, 90],
       [55, 34, 29, 49],
       [ 6, 21, 53, 42]])

In [ ]:
arr>=80

array([[False, False, False, False],
       [ True, False, False, False],
       [ True, False,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
arr[arr>=80]

array([87, 84, 80, 90])

In [ ]:
arr[(arr>=80) & (arr%2!=0)]

array([87])

In [ ]:
arr[(arr>=80) & (arr%2!=0)]=0
arr

array([[62, 53, 21,  8],
       [ 0, 56, 24, 53],
       [84, 61, 80, 90],
       [55, 34, 29, 49],
       [ 6, 21, 53, 42]])